@startuml DER

entity User {
    id BIGINT <<PK>>
    isAdmin BOOLEAN
    selectedAvatar INT <<FK>>
    nickname VARCHAR(20) <<UK>>
    password TEXT
    xp INT
    --
}

entity Avatar {
    id INT <<PK>>
    name VARCHAR(30) <<UK>>
    filename TEXT <<UK>>
    --
}

entity UserAvatar {
    userId BIGINT <<FK>>
    AvatarId INT <<FK>>
    --
}

entity Photo {
    id BIGINT <<PK>>
    userId BIGINT <<FK>>
    filename TEXT <<UK>>
    latitude FLOAT
    longitude FLOAT
    --
}

User ||--o{ Photo
User --|| Avatar
User --o{ UserAvatar
Avatar --o{ UserAvatar

@enduml