@startuml DER

entity User {
    id INT <<PK>>
    isAdmin BOOLEAN
    selectedAvatar INT <<FK>>
    nickname VARCHAR(20) <<UK>>
    password TEXT
    XP INT
    --
}

entity Avatar {
    id INT <<PK>>
    name VARCHAR(30) <<UK>>
    path TEXT
    --
}

entity UserAvatar {
    userId INT <<FK>>
    AvatarId <<FK>>
    --
}

entity Photo {
    id INT <<PK>>
    userId INT <<FK>>
    path TEXT
    fileName <<UK>>
    latitude FLOAT
    longitude FLOAT
    --
}

User ||--o{ Photo
User --|| Avatar
User --o{ UserAvatar
Avatar --o{ UserAvatar

@enduml