@startuml DER

entity User {
    id INT <<PK>>
    isAdmin BOOLEAN
    nickname VARCHAR(20) <<UK>>
    password VARCHAR(20)
    XP INT
    --
}

entity Avatar {
    id INT <<PK>>
    name VARCHAR(30) <<UK>>
    path TEXT
    --
}

entity UserAvatar {
    userId INT <<FK>>
    AvatarId <<FK>>
    --
}

entity UserPhoto {
    userId INT <<FK>>
    PhotoId INT <<FK>>
    --
}

entity Photo {
    id INT <<PK>>
    userId INT <<FK>>
    path TEXT
    fileName <<UK>>
    latitude FLOAT
    longitude FLOAT
    --
}

User --o{ UserPhoto
User --o{ UserAvatar
Avatar --o{ UserAvatar
Photo --o{ UserPhoto

@enduml